// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright 2025 Carabiner Systems, Inc

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: osv.proto

package osv

import (
	v1 "github.com/carabiner-dev/osv/go/osv/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Results describes the OSV scanner format output
type Results struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Results       []*Result              `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"` // google.protobuf.Struct experimental_config = 3;
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Results) Reset() {
	*x = Results{}
	mi := &file_osv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Results) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Results) ProtoMessage() {}

func (x *Results) ProtoReflect() protoreflect.Message {
	mi := &file_osv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Results.ProtoReflect.Descriptor instead.
func (*Results) Descriptor() ([]byte, []int) {
	return file_osv_proto_rawDescGZIP(), []int{0}
}

func (x *Results) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *Results) GetResults() []*Result {
	if x != nil {
		return x.Results
	}
	return nil
}

type Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        *Result_Source         `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Packages      []*Result_Package      `protobuf:"bytes,2,rep,name=packages,proto3" json:"packages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_osv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_osv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_osv_proto_rawDescGZIP(), []int{1}
}

func (x *Result) GetSource() *Result_Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *Result) GetPackages() []*Result_Package {
	if x != nil {
		return x.Packages
	}
	return nil
}

type Result_Package struct {
	state           protoimpl.MessageState  `protogen:"open.v1"`
	Package         *Result_Package_Info    `protobuf:"bytes,1,opt,name=package,proto3" json:"package,omitempty"`
	Vulnerabilities []*v1.Record            `protobuf:"bytes,2,rep,name=vulnerabilities,proto3" json:"vulnerabilities,omitempty"`
	Groups          []*Result_Package_Group `protobuf:"bytes,3,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Result_Package) Reset() {
	*x = Result_Package{}
	mi := &file_osv_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result_Package) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result_Package) ProtoMessage() {}

func (x *Result_Package) ProtoReflect() protoreflect.Message {
	mi := &file_osv_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result_Package.ProtoReflect.Descriptor instead.
func (*Result_Package) Descriptor() ([]byte, []int) {
	return file_osv_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Result_Package) GetPackage() *Result_Package_Info {
	if x != nil {
		return x.Package
	}
	return nil
}

func (x *Result_Package) GetVulnerabilities() []*v1.Record {
	if x != nil {
		return x.Vulnerabilities
	}
	return nil
}

func (x *Result_Package) GetGroups() []*Result_Package_Group {
	if x != nil {
		return x.Groups
	}
	return nil
}

type Result_Source struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result_Source) Reset() {
	*x = Result_Source{}
	mi := &file_osv_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result_Source) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result_Source) ProtoMessage() {}

func (x *Result_Source) ProtoReflect() protoreflect.Message {
	mi := &file_osv_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result_Source.ProtoReflect.Descriptor instead.
func (*Result_Source) Descriptor() ([]byte, []int) {
	return file_osv_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Result_Source) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Result_Source) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type Result_Package_Info struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Ecosystem     string                 `protobuf:"bytes,3,opt,name=ecosystem,proto3" json:"ecosystem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result_Package_Info) Reset() {
	*x = Result_Package_Info{}
	mi := &file_osv_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result_Package_Info) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result_Package_Info) ProtoMessage() {}

func (x *Result_Package_Info) ProtoReflect() protoreflect.Message {
	mi := &file_osv_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result_Package_Info.ProtoReflect.Descriptor instead.
func (*Result_Package_Info) Descriptor() ([]byte, []int) {
	return file_osv_proto_rawDescGZIP(), []int{1, 0, 0}
}

func (x *Result_Package_Info) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Result_Package_Info) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Result_Package_Info) GetEcosystem() string {
	if x != nil {
		return x.Ecosystem
	}
	return ""
}

type Result_Package_Group struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Ids                  []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	Aliases              []string               `protobuf:"bytes,2,rep,name=aliases,proto3" json:"aliases,omitempty"`
	MaxSeverity          string                 `protobuf:"bytes,3,opt,name=max_severity,json=maxSeverity,proto3" json:"max_severity,omitempty"`
	ExperimentalAnalysis *structpb.Struct       `protobuf:"bytes,4,opt,name=experimentalAnalysis,proto3" json:"experimentalAnalysis,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Result_Package_Group) Reset() {
	*x = Result_Package_Group{}
	mi := &file_osv_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result_Package_Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result_Package_Group) ProtoMessage() {}

func (x *Result_Package_Group) ProtoReflect() protoreflect.Message {
	mi := &file_osv_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result_Package_Group.ProtoReflect.Descriptor instead.
func (*Result_Package_Group) Descriptor() ([]byte, []int) {
	return file_osv_proto_rawDescGZIP(), []int{1, 0, 1}
}

func (x *Result_Package_Group) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *Result_Package_Group) GetAliases() []string {
	if x != nil {
		return x.Aliases
	}
	return nil
}

func (x *Result_Package_Group) GetMaxSeverity() string {
	if x != nil {
		return x.MaxSeverity
	}
	return ""
}

func (x *Result_Package_Group) GetExperimentalAnalysis() *structpb.Struct {
	if x != nil {
		return x.ExperimentalAnalysis
	}
	return nil
}

var File_osv_proto protoreflect.FileDescriptor

const file_osv_proto_rawDesc = "" +
	"\n" +
	"\tosv.proto\x12\x03osv\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\bv1.proto\"`\n" +
	"\aResults\x12.\n" +
	"\x04date\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\x12%\n" +
	"\aresults\x18\x02 \x03(\v2\v.osv.ResultR\aresults\"\xbe\x04\n" +
	"\x06Result\x12*\n" +
	"\x06source\x18\x01 \x01(\v2\x12.osv.Result.SourceR\x06source\x12/\n" +
	"\bpackages\x18\x02 \x03(\v2\x13.osv.Result.PackageR\bpackages\x1a\xa4\x03\n" +
	"\aPackage\x122\n" +
	"\apackage\x18\x01 \x01(\v2\x18.osv.Result.Package.InfoR\apackage\x128\n" +
	"\x0fvulnerabilities\x18\x02 \x03(\v2\x0e.osv.v1.RecordR\x0fvulnerabilities\x121\n" +
	"\x06groups\x18\x03 \x03(\v2\x19.osv.Result.Package.GroupR\x06groups\x1aR\n" +
	"\x04Info\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1c\n" +
	"\tecosystem\x18\x03 \x01(\tR\tecosystem\x1a\xa3\x01\n" +
	"\x05Group\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\x12\x18\n" +
	"\aaliases\x18\x02 \x03(\tR\aaliases\x12!\n" +
	"\fmax_severity\x18\x03 \x01(\tR\vmaxSeverity\x12K\n" +
	"\x14experimentalAnalysis\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x14experimentalAnalysis\x1a0\n" +
	"\x06Source\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04typeBd\n" +
	"\acom.osvB\bOsvProtoP\x01Z#github.com/carabiner-dev/osv/go/osv\xa2\x02\x03OXX\xaa\x02\x03Osv\xca\x02\x03Osv\xe2\x02\x0fOsv\\GPBMetadata\xea\x02\x03Osvb\x06proto3"

var (
	file_osv_proto_rawDescOnce sync.Once
	file_osv_proto_rawDescData []byte
)

func file_osv_proto_rawDescGZIP() []byte {
	file_osv_proto_rawDescOnce.Do(func() {
		file_osv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_osv_proto_rawDesc), len(file_osv_proto_rawDesc)))
	})
	return file_osv_proto_rawDescData
}

var file_osv_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_osv_proto_goTypes = []any{
	(*Results)(nil),               // 0: osv.Results
	(*Result)(nil),                // 1: osv.Result
	(*Result_Package)(nil),        // 2: osv.Result.Package
	(*Result_Source)(nil),         // 3: osv.Result.Source
	(*Result_Package_Info)(nil),   // 4: osv.Result.Package.Info
	(*Result_Package_Group)(nil),  // 5: osv.Result.Package.Group
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
	(*v1.Record)(nil),             // 7: osv.v1.Record
	(*structpb.Struct)(nil),       // 8: google.protobuf.Struct
}
var file_osv_proto_depIdxs = []int32{
	6, // 0: osv.Results.date:type_name -> google.protobuf.Timestamp
	1, // 1: osv.Results.results:type_name -> osv.Result
	3, // 2: osv.Result.source:type_name -> osv.Result.Source
	2, // 3: osv.Result.packages:type_name -> osv.Result.Package
	4, // 4: osv.Result.Package.package:type_name -> osv.Result.Package.Info
	7, // 5: osv.Result.Package.vulnerabilities:type_name -> osv.v1.Record
	5, // 6: osv.Result.Package.groups:type_name -> osv.Result.Package.Group
	8, // 7: osv.Result.Package.Group.experimentalAnalysis:type_name -> google.protobuf.Struct
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_osv_proto_init() }
func file_osv_proto_init() {
	if File_osv_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_osv_proto_rawDesc), len(file_osv_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_osv_proto_goTypes,
		DependencyIndexes: file_osv_proto_depIdxs,
		MessageInfos:      file_osv_proto_msgTypes,
	}.Build()
	File_osv_proto = out.File
	file_osv_proto_goTypes = nil
	file_osv_proto_depIdxs = nil
}
